###
POST http://localhost:2700/productos HTTP/1.1
Content-Type: application/json

{
"nombre":"reloj",
"descripcion": "casio",
"precio":"1000",
"cantstock": "20"
}
###
GET http://localhost:2700/productos HTTP/1.1

###
DELETE http://localhost:2700/productos/:id HTTP/1.1
### 
PUT http://localhost:2700/productos/:id HTTP/1.1
Content-Type: application/json
{
"nombre":"reloj",
"descripcion": "rolex",
"precio":"10000",
"cantstock": "2"
}